# Descarrega una imatge base amb Apache i PHP 8.3
FROM php:8.2-apache

# Defineix el directori de treball
WORKDIR /var/www/html

# Copia la carpeta app dins del contenidor
COPY app .

# Exposa el port 80/tcp
EXPOSE 80
